on: pull_request
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site

    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
      
      - name: Test Gatsby build
        run: gatsby build