on: pull_request
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 19.8.1

      - name: Install dependencies
        run: npm install --force && npm install -g gatsby-cli

      - name: Test Gatsby build
        run: gatsby build
